name: Run Playwright + Gitea in Docker

on:
  workflow_dispatch: 

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Run Docker Compose (build & test)
        run: |
          docker compose up --abort-on-container-exit --remove-orphans --build

      - name: Clean up containers
        run: |
          docker compose down --volumes --remove-orphans

      - name: Upload Playwright report
        if: always() # run even if tests fail
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: ./playwright-report